# Generated by Django 4.1.5 on 2023-01-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('ingredientes', models.CharField(max_length=2000)),
                ('details_link', models.URLField(max_length=2000)),
                ('credits', models.CharField(max_length=1000)),
            ],
        ),
    ]
