# Generated by Django 4.1.5 on 2023-01-21 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rr_app', '0002_rename_ingredientes_recipes_ingredients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
    ]
